-- ============================================================
-- COMPLETE ADMIN TABLES - Subscription Plans + Pay-Per-Hire Model
-- Run this ENTIRE script in Supabase SQL Editor
-- ============================================================

-- ========================
-- 1. SUBSCRIPTION PLANS
-- ========================
CREATE TABLE IF NOT EXISTS subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price_inr DECIMAL(10,2) DEFAULT 0,
  price_usd DECIMAL(10,2) DEFAULT 0,
  duration TEXT DEFAULT 'Monthly',
  is_active BOOLEAN DEFAULT true,
  job_posts_limit INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================
-- 2. SALARY SLABS (Pay-Per-Hire Pricing)
-- ========================
CREATE TABLE IF NOT EXISTS salary_slabs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  min_salary DECIMAL(12,2) DEFAULT 0,
  max_salary DECIMAL(12,2) DEFAULT 0,
  pph_fee DECIMAL(10,2) DEFAULT 0,
  currency TEXT DEFAULT 'INR',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================
-- 3. CUSTOM CORPORATE PLANS (PPH Custom Deals)
-- ========================
CREATE TABLE IF NOT EXISTS custom_corporate_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT,
  company_name TEXT NOT NULL,
  custom_price_per_hire DECIMAL(10,2) DEFAULT 0,
  payment_cycle TEXT CHECK (payment_cycle IN ('weekly', 'monthly', 'quarterly')) DEFAULT 'monthly',
  advance_percentage DECIMAL(5,2) DEFAULT 0,
  post_payment_percentage DECIMAL(5,2) DEFAULT 100,
  replacement_period_days INTEGER DEFAULT 90,
  bulk_discount_tiers JSONB DEFAULT '[]',
  special_terms TEXT,
  agreement_pdf_url TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================
-- 4. PPH PAYMENT OPTIONS
-- ========================
CREATE TABLE IF NOT EXISTS pph_payment_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT CHECK (type IN ('advance', 'postPayment')) DEFAULT 'advance',
  discount_min DECIMAL(5,2) DEFAULT 0,
  discount_max DECIMAL(5,2) DEFAULT 0,
  allow_customization BOOLEAN DEFAULT false,
  payment_term_days INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================
-- 5. AGREEMENT TEMPLATES (PPH Contracts)
-- ========================
CREATE TABLE IF NOT EXISTS agreement_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('standard', 'custom')) DEFAULT 'standard',
  content TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================
-- 6. PPH TRANSACTIONS (Track Pay-Per-Hire Payments)
-- ========================
CREATE TABLE IF NOT EXISTS pph_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT,
  candidate_id TEXT,
  job_id BIGINT,
  salary_offered DECIMAL(12,2) DEFAULT 0,
  pph_fee DECIMAL(10,2) DEFAULT 0,
  advance_amount DECIMAL(10,2) DEFAULT 0,
  post_payment_amount DECIMAL(10,2) DEFAULT 0,
  payment_status TEXT CHECK (payment_status IN ('pending', 'advance_paid', 'completed', 'refunded', 'cancelled')) DEFAULT 'pending',
  hired_date TIMESTAMP WITH TIME ZONE,
  replacement_deadline TIMESTAMP WITH TIME ZONE,
  agreement_template_id BIGINT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================
-- 7. SYSTEM LOGS
-- ========================
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT DEFAULT 'INFO',
  message TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================
-- 8. API KEYS
-- ========================
CREATE TABLE IF NOT EXISTS api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  api_key TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================
-- ENABLE ROW LEVEL SECURITY
-- ========================
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE salary_slabs ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_corporate_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE pph_payment_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE agreement_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE pph_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;

-- ========================
-- PUBLIC ACCESS POLICIES
-- ========================
CREATE POLICY "Public Access subscription_plans" ON subscription_plans FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access salary_slabs" ON salary_slabs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access custom_corporate_plans" ON custom_corporate_plans FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access pph_payment_options" ON pph_payment_options FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access agreement_templates" ON agreement_templates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access pph_transactions" ON pph_transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access system_logs" ON system_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access api_keys" ON api_keys FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- DONE! All tables created:
-- 1. subscription_plans     - Stores your pricing plans
-- 2. salary_slabs           - PPH salary-based pricing tiers
-- 3. custom_corporate_plans - Custom deals for specific companies
-- 4. pph_payment_options    - Advance/post-payment settings
-- 5. agreement_templates    - PPH contract templates
-- 6. pph_transactions       - Tracks all PPH hire payments
-- 7. system_logs            - Admin system logs
-- 8. api_keys               - AI provider API keys
-- ============================================================
