-- ============================================================
-- ENGAGEMENT FEATURES TABLES
-- ============================================================

-- 1. CONVERSATIONS
-- Aggregates chats between a candidate and an employer, optionally linked to a job or application.
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    employer_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_id BIGINT REFERENCES employer_job_posts(id) ON DELETE SET NULL,
    application_id BIGINT REFERENCES job_applications(id) ON DELETE SET NULL,
    last_message_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT CHECK (status IN ('active', 'archived', 'blocked')) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(candidate_id, employer_id, job_id)
);

CREATE INDEX IF NOT EXISTS idx_conversations_candidate ON conversations(candidate_id);
CREATE INDEX IF NOT EXISTS idx_conversations_employer ON conversations(employer_id);
CREATE INDEX IF NOT EXISTS idx_conversations_updated ON conversations(last_message_at);

-- 2. MESSAGES
-- Individual messages within a conversation.
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id TEXT NOT NULL REFERENCES users(id),
    sender_type TEXT CHECK (sender_type IN ('candidate', 'employer', 'system')) NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    read_at TIMESTAMP WITH TIME ZONE,
    attachments JSONB DEFAULT '[]', -- For file uploads
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_unread ON messages(conversation_id, sender_id) WHERE is_read = false;

-- 3. NOTIFICATIONS (Enhancement if not exists, though fresh_install has it)
-- Ensure strict schema if not already present or modify if needed.
-- (Assuming notifications table exists from fresh_install.sql, skipping creation but adding indexes if needed)

-- 4. ENABLE RLS
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICIES
-- Conversations
CREATE POLICY "Users can view their own conversations" ON conversations
    FOR SELECT USING (auth.uid() = candidate_id OR auth.uid() = employer_id);

CREATE POLICY "Users can insert conversations they are part of" ON conversations
    FOR INSERT WITH CHECK (auth.uid() = candidate_id OR auth.uid() = employer_id);

CREATE POLICY "Users can update their own conversations" ON conversations
    FOR UPDATE USING (auth.uid() = candidate_id OR auth.uid() = employer_id);

-- Messages
CREATE POLICY "Users can view messages in their conversations" ON messages
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM conversations c 
            WHERE c.id = messages.conversation_id 
            AND (c.candidate_id = auth.uid() OR c.employer_id = auth.uid())
        )
    );

CREATE POLICY "Users can send messages to their conversations" ON messages
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM conversations c 
            WHERE c.id = conversation_id 
            AND (c.candidate_id = auth.uid() OR c.employer_id = auth.uid())
        )
        AND sender_id = auth.uid()
    );

-- 6. REALTIME
-- Enable realtime for messages to support chat
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table conversations;
