-- Fix RLS policy for users table
-- The /api/jobs endpoint JOINs users table via employer_job_posts_employer_id_fkey
-- Without a SELECT policy, this JOIN fails with "permission denied for table users"

-- Allow public read access to basic user info (needed for job listings, profiles, etc.)
CREATE POLICY "Allow read access to users" ON users FOR SELECT USING (true);

-- If you also need candidate_experience and candidate_skills tables:
CREATE TABLE IF NOT EXISTS candidate_experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  company_name TEXT,
  job_title TEXT,
  location TEXT,
  start_date DATE,
  end_date DATE,
  is_current BOOLEAN DEFAULT false,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cand_exp_user ON candidate_experience(user_id);

CREATE TABLE IF NOT EXISTS candidate_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  skill TEXT NOT NULL,
  level TEXT CHECK (level IN ('beginner','intermediate','advanced','expert')) DEFAULT 'intermediate',
  years_experience INTEGER DEFAULT 0,
  is_primary BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cand_skills_user ON candidate_skills(user_id);

-- RLS for new tables
ALTER TABLE candidate_experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access to candidate_experience" ON candidate_experience FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to candidate_skills" ON candidate_skills FOR ALL USING (true) WITH CHECK (true);

-- Also create assessment_results if not exists (referenced by candidate stats and video resume)
CREATE TABLE IF NOT EXISTS assessment_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  course_id BIGINT,
  assessment_type TEXT DEFAULT 'general',
  score INTEGER,
  max_score INTEGER DEFAULT 100,
  answers JSONB DEFAULT '[]',
  time_taken_seconds INTEGER,
  passed BOOLEAN DEFAULT false,
  certificate_issued BOOLEAN DEFAULT false,
  video_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_results_user ON assessment_results(user_id);

ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access to assessment_results" ON assessment_results FOR ALL USING (true) WITH CHECK (true);

-- Ensure conversations and messages tables exist for messaging
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_1 TEXT REFERENCES users(id) ON DELETE CASCADE,
  participant_2 TEXT REFERENCES users(id) ON DELETE CASCADE,
  last_message TEXT,
  last_message_at TIMESTAMP WITH TIME ZONE,
  unread_count_1 INTEGER DEFAULT 0,
  unread_count_2 INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_conv_p1 ON conversations(participant_1);
CREATE INDEX IF NOT EXISTS idx_conv_p2 ON conversations(participant_2);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id TEXT REFERENCES users(id),
  content TEXT,
  message_type TEXT DEFAULT 'text',
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_msg_conv ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_msg_sender ON messages(sender_id);

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access to conversations" ON conversations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to messages" ON messages FOR ALL USING (true) WITH CHECK (true);
