-- ============================================================
-- HIREGO AI - FRESH INSTALL (DROPS EVERYTHING FIRST)
-- WARNING: This will DELETE all existing data!
-- Run this ONLY on a fresh database or if you want to reset
-- ============================================================

-- DROP ALL POLICIES FIRST
DO $$ 
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'DROP POLICY IF EXISTS "Public Access" ON ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;
END $$;

-- DROP ALL EXISTING TABLES (CASCADE removes all dependencies)
DROP TABLE IF EXISTS email_logs CASCADE;
DROP TABLE IF EXISTS routes_registry CASCADE;
DROP TABLE IF EXISTS analytics CASCADE;
DROP TABLE IF EXISTS platform_reports CASCADE;
DROP TABLE IF EXISTS admin_settings CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS crm_leads CASCADE;
DROP TABLE IF EXISTS staff_activity CASCADE;
DROP TABLE IF EXISTS staff_users CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS wallet_transactions CASCADE;
DROP TABLE IF EXISTS wallet CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS pay_per_hire_records CASCADE;
DROP TABLE IF EXISTS employer_subscriptions CASCADE;
DROP TABLE IF EXISTS subscription_plans CASCADE;
DROP TABLE IF EXISTS session_recordings CASCADE;
DROP TABLE IF EXISTS video_interview_sessions CASCADE;
DROP TABLE IF EXISTS interview_feedback CASCADE;
DROP TABLE IF EXISTS interview_logs CASCADE;
DROP TABLE IF EXISTS interviews CASCADE;
DROP TABLE IF EXISTS screening_results CASCADE;
DROP TABLE IF EXISTS job_applications CASCADE;
DROP TABLE IF EXISTS employer_activity_log CASCADE;
DROP TABLE IF EXISTS employer_job_posts CASCADE;
DROP TABLE IF EXISTS employers CASCADE;
DROP TABLE IF EXISTS educator_payouts CASCADE;
DROP TABLE IF EXISTS educators CASCADE;
DROP TABLE IF EXISTS live_classes CASCADE;
DROP TABLE IF EXISTS assignment_submissions CASCADE;
DROP TABLE IF EXISTS course_assignments CASCADE;
DROP TABLE IF EXISTS course_quizzes CASCADE;
DROP TABLE IF EXISTS course_lessons CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS candidate_activity_log CASCADE;
DROP TABLE IF EXISTS candidate_assessments CASCADE;
DROP TABLE IF EXISTS candidate_certificates CASCADE;
DROP TABLE IF EXISTS candidate_progress CASCADE;
DROP TABLE IF EXISTS candidates CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Also drop old tables that might exist
DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS applications CASCADE;
DROP TABLE IF EXISTS assessment_results CASCADE;
DROP TABLE IF EXISTS candidate_experience CASCADE;
DROP TABLE IF EXISTS candidate_skills CASCADE;
DROP TABLE IF EXISTS credit_bundles CASCADE;
DROP TABLE IF EXISTS job_post_types CASCADE;
DROP TABLE IF EXISTS salary_slabs CASCADE;
DROP TABLE IF EXISTS system_logs CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS custom_corporate_plans CASCADE;
DROP TABLE IF EXISTS pph_payment_options CASCADE;
DROP TABLE IF EXISTS agreement_templates CASCADE;
DROP TABLE IF EXISTS pph_transactions CASCADE;

-- ============================================================
-- NOW CREATE ALL TABLES (42 TABLES)
-- ============================================================

-- 1. USERS
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  phone TEXT,
  role TEXT CHECK (role IN ('candidate','employer','admin','staff','educator')) DEFAULT 'candidate',
  status TEXT CHECK (status IN ('Active','Pending','Blocked','Suspended','Deleted')) DEFAULT 'Active',
  avatar_url TEXT,
  country TEXT DEFAULT 'IN',
  currency TEXT DEFAULT 'INR',
  timezone TEXT DEFAULT 'Asia/Kolkata',
  last_login TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

-- 2. USER_PROFILES
CREATE TABLE user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  bio TEXT,
  title TEXT,
  location TEXT,
  date_of_birth DATE,
  gender TEXT,
  current_address TEXT,
  permanent_address TEXT,
  linkedin_url TEXT,
  github_url TEXT,
  portfolio_url TEXT,
  resume_url TEXT,
  skills JSONB DEFAULT '[]',
  languages JSONB DEFAULT '[]',
  preferences JSONB DEFAULT '{}',
  profile_completion INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_profiles_user ON user_profiles(user_id);

-- 3. CANDIDATES
CREATE TABLE candidates (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  email TEXT,
  name TEXT,
  phone TEXT,
  job_profile TEXT,
  education_10th JSONB,
  education_12th JSONB,
  graduation JSONB,
  post_graduation JSONB,
  experience JSONB DEFAULT '[]',
  certifications JSONB DEFAULT '[]',
  desired_salary_min DECIMAL(12,2),
  desired_salary_max DECIMAL(12,2),
  desired_locations JSONB DEFAULT '[]',
  work_mode_pref TEXT CHECK (work_mode_pref IN ('Remote','On-site','Hybrid','Any')) DEFAULT 'Any',
  availability TEXT DEFAULT 'Immediate',
  match_score INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CANDIDATE_PROGRESS
CREATE TABLE candidate_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  course_id BIGINT,
  lesson_id BIGINT,
  quiz_id BIGINT,
  progress_pct INTEGER DEFAULT 0,
  status TEXT CHECK (status IN ('not_started','in_progress','completed')) DEFAULT 'not_started',
  score INTEGER,
  time_spent_mins INTEGER DEFAULT 0,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_candidate_progress_user ON candidate_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_candidate_progress_course ON candidate_progress(course_id);

-- 5. CANDIDATE_CERTIFICATES
CREATE TABLE candidate_certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  course_id BIGINT,
  certificate_url TEXT,
  certificate_code TEXT UNIQUE,
  issued_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expiry_date TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_candidate_certs_user ON candidate_certificates(user_id);

-- 6. CANDIDATE_ASSESSMENTS
CREATE TABLE candidate_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  job_id BIGINT,
  assessment_type TEXT CHECK (assessment_type IN ('technical','behavioral','aptitude','coding','video','voice')) DEFAULT 'technical',
  score INTEGER,
  max_score INTEGER DEFAULT 100,
  communication_score INTEGER,
  knowledge_score INTEGER,
  confidence_score INTEGER,
  score_breakdown JSONB DEFAULT '{}',
  transcript TEXT,
  status TEXT CHECK (status IN ('pending','in_progress','completed','expired')) DEFAULT 'pending',
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cand_assess_user ON candidate_assessments(user_id);
CREATE INDEX IF NOT EXISTS idx_cand_assess_job ON candidate_assessments(job_id);

-- 7. CANDIDATE_ACTIVITY_LOG
CREATE TABLE candidate_activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  metadata JSONB DEFAULT '{}',
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cand_activity_user ON candidate_activity_log(user_id);
CREATE INDEX IF NOT EXISTS idx_cand_activity_date ON candidate_activity_log(created_at);

-- 8. COURSES
CREATE TABLE courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  sub_category TEXT,
  thumbnail_url TEXT,
  educator_id TEXT,
  difficulty TEXT CHECK (difficulty IN ('Beginner','Intermediate','Advanced','Expert')) DEFAULT 'Beginner',
  duration_hours INTEGER DEFAULT 0,
  price_inr DECIMAL(10,2) DEFAULT 0,
  price_usd DECIMAL(10,2) DEFAULT 0,
  is_free BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT false,
  is_featured BOOLEAN DEFAULT false,
  tags JSONB DEFAULT '[]',
  skills_covered JSONB DEFAULT '[]',
  enrollment_count INTEGER DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0,
  status TEXT CHECK (status IN ('draft','published','archived','under_review')) DEFAULT 'draft',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_courses_category ON courses(category);
CREATE INDEX IF NOT EXISTS idx_courses_status ON courses(status);

-- 9. COURSE_LESSONS
CREATE TABLE course_lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  content_type TEXT CHECK (content_type IN ('video','text','pdf','interactive','quiz')) DEFAULT 'video',
  content_url TEXT,
  content_text TEXT,
  duration_mins INTEGER DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  is_free_preview BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_lessons_course ON course_lessons(course_id);

-- 10. COURSE_QUIZZES
CREATE TABLE course_quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  lesson_id BIGINT REFERENCES course_lessons(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  questions JSONB DEFAULT '[]',
  passing_score INTEGER DEFAULT 60,
  time_limit_mins INTEGER DEFAULT 30,
  max_attempts INTEGER DEFAULT 3,
  sort_order INTEGER DEFAULT 0,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_quizzes_course ON course_quizzes(course_id);

-- 11. COURSE_ASSIGNMENTS
CREATE TABLE course_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  instructions TEXT,
  due_date TIMESTAMP WITH TIME ZONE,
  max_score INTEGER DEFAULT 100,
  rubric JSONB DEFAULT '{}',
  attachments JSONB DEFAULT '[]',
  sort_order INTEGER DEFAULT 0,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_assignments_course ON course_assignments(course_id);

-- 12. ASSIGNMENT_SUBMISSIONS
CREATE TABLE assignment_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT REFERENCES course_assignments(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  submission_url TEXT,
  submission_text TEXT,
  attachments JSONB DEFAULT '[]',
  score INTEGER,
  feedback TEXT,
  graded_by TEXT REFERENCES users(id),
  status TEXT CHECK (status IN ('submitted','under_review','graded','returned','late')) DEFAULT 'submitted',
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  graded_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_submissions_assignment ON assignment_submissions(assignment_id);
CREATE INDEX IF NOT EXISTS idx_submissions_user ON assignment_submissions(user_id);

-- 13. LIVE_CLASSES
CREATE TABLE live_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  educator_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
  duration_mins INTEGER DEFAULT 60,
  meeting_url TEXT,
  recording_url TEXT,
  max_attendees INTEGER DEFAULT 100,
  current_attendees INTEGER DEFAULT 0,
  status TEXT CHECK (status IN ('scheduled','live','completed','cancelled')) DEFAULT 'scheduled',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_live_classes_course ON live_classes(course_id);

-- 14. EDUCATORS
CREATE TABLE educators (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  display_name TEXT,
  specialization TEXT,
  bio TEXT,
  qualification TEXT,
  experience_years INTEGER DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0,
  total_students INTEGER DEFAULT 0,
  total_courses INTEGER DEFAULT 0,
  total_earnings DECIMAL(12,2) DEFAULT 0,
  payout_method TEXT DEFAULT 'bank_transfer',
  payout_details JSONB DEFAULT '{}',
  is_verified BOOLEAN DEFAULT false,
  is_featured BOOLEAN DEFAULT false,
  social_links JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 15. EDUCATOR_PAYOUTS
CREATE TABLE educator_payouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  educator_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  currency TEXT DEFAULT 'INR',
  payout_method TEXT DEFAULT 'bank_transfer',
  reference_id TEXT,
  status TEXT CHECK (status IN ('pending','processing','completed','failed','cancelled')) DEFAULT 'pending',
  period_start DATE,
  period_end DATE,
  breakdown JSONB DEFAULT '{}',
  processed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_edu_payouts_educator ON educator_payouts(educator_id);

-- 16. EMPLOYERS
CREATE TABLE employers (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  company_name TEXT NOT NULL,
  company_logo TEXT,
  company_website TEXT,
  industry TEXT,
  company_size TEXT,
  description TEXT,
  hq_location TEXT,
  country TEXT DEFAULT 'IN',
  gst_number TEXT,
  pan_number TEXT,
  contact_person TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  is_verified BOOLEAN DEFAULT false,
  verification_docs JSONB DEFAULT '[]',
  social_links JSONB DEFAULT '{}',
  subscription_plan_id BIGINT,
  job_posts_count INTEGER DEFAULT 0,
  job_posts_limit INTEGER DEFAULT 5,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 17. EMPLOYER_JOB_POSTS
CREATE TABLE employer_job_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  requirements TEXT,
  responsibilities TEXT,
  skills JSONB DEFAULT '[]',
  location TEXT,
  country TEXT DEFAULT 'IN',
  work_mode TEXT CHECK (work_mode IN ('On-site','Remote','Hybrid')) DEFAULT 'Remote',
  employment_type TEXT CHECK (employment_type IN ('Full-time','Part-time','Contract','Freelance','Internship')) DEFAULT 'Full-time',
  experience_min INTEGER DEFAULT 0,
  experience_max INTEGER,
  salary_min DECIMAL(12,2),
  salary_max DECIMAL(12,2),
  salary_currency TEXT DEFAULT 'INR',
  education_required JSONB DEFAULT '[]',
  benefits JSONB DEFAULT '[]',
  job_type TEXT DEFAULT 'free',
  plan_id BIGINT,
  status TEXT CHECK (status IN ('active','draft','closed','archived','expired','under_review')) DEFAULT 'active',
  is_featured BOOLEAN DEFAULT false,
  is_urgent BOOLEAN DEFAULT false,
  application_count INTEGER DEFAULT 0,
  views_count INTEGER DEFAULT 0,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_jobs_employer ON employer_job_posts(employer_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON employer_job_posts(status);
CREATE INDEX IF NOT EXISTS idx_jobs_type ON employer_job_posts(job_type);
CREATE INDEX IF NOT EXISTS idx_jobs_location ON employer_job_posts(location);
CREATE INDEX IF NOT EXISTS idx_jobs_created ON employer_job_posts(created_at);

-- 18. EMPLOYER_ACTIVITY_LOG
CREATE TABLE employer_activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  metadata JSONB DEFAULT '{}',
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_emp_activity_employer ON employer_activity_log(employer_id);

-- 19. JOB_APPLICATIONS
CREATE TABLE job_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES employer_job_posts(id) ON DELETE CASCADE,
  candidate_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  resume_url TEXT,
  cover_letter TEXT,
  match_score INTEGER,
  ai_screening_score INTEGER,
  status TEXT CHECK (status IN ('applied','pending','screened','shortlisted','interview_scheduled','interviewed','offered','hired','rejected','withdrawn')) DEFAULT 'applied',
  rejection_reason TEXT,
  notes TEXT,
  metadata JSONB DEFAULT '{}',
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(job_id, candidate_id)
);
CREATE INDEX IF NOT EXISTS idx_applications_job ON job_applications(job_id);
CREATE INDEX IF NOT EXISTS idx_applications_candidate ON job_applications(candidate_id);
CREATE INDEX IF NOT EXISTS idx_applications_status ON job_applications(status);

-- 20. SCREENING_RESULTS
CREATE TABLE screening_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT REFERENCES job_applications(id) ON DELETE CASCADE,
  candidate_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES employer_job_posts(id),
  screening_type TEXT CHECK (screening_type IN ('ai_resume','ai_skill','ai_behavioral','manual','coding_test')) DEFAULT 'ai_resume',
  overall_score INTEGER,
  skill_match_score INTEGER,
  experience_match_score INTEGER,
  education_match_score INTEGER,
  score_breakdown JSONB DEFAULT '{}',
  ai_summary TEXT,
  recommendation TEXT CHECK (recommendation IN ('strong_yes','yes','maybe','no','strong_no')),
  screened_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_screening_app ON screening_results(application_id);

-- 21. INTERVIEWS
CREATE TABLE interviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT REFERENCES job_applications(id) ON DELETE CASCADE,
  candidate_id TEXT REFERENCES users(id),
  employer_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES employer_job_posts(id),
  scheduled_date TIMESTAMP WITH TIME ZONE,
  duration INTEGER DEFAULT 60,
  round TEXT CHECK (round IN ('screening','technical','behavioral','hr','final','group')) DEFAULT 'screening',
  type TEXT CHECK (type IN ('Video','Phone','In-Person','AI-Proctored','Take-Home')) DEFAULT 'Video',
  meeting_link TEXT,
  status TEXT CHECK (status IN ('scheduled','in_progress','completed','cancelled','no_show','rescheduled')) DEFAULT 'scheduled',
  score INTEGER,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_interviews_candidate ON interviews(candidate_id);
CREATE INDEX IF NOT EXISTS idx_interviews_job ON interviews(job_id);
CREATE INDEX IF NOT EXISTS idx_interviews_status ON interviews(status);
CREATE INDEX IF NOT EXISTS idx_interviews_date ON interviews(scheduled_date);

-- 22. INTERVIEW_LOGS
CREATE TABLE interview_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  event_data JSONB DEFAULT '{}',
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_interview_logs_interview ON interview_logs(interview_id);

-- 23. INTERVIEW_FEEDBACK
CREATE TABLE interview_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id) ON DELETE CASCADE,
  interviewer_id TEXT REFERENCES users(id),
  overall_rating INTEGER CHECK (overall_rating >= 1 AND overall_rating <= 5),
  technical_score INTEGER,
  communication_score INTEGER,
  cultural_fit_score INTEGER,
  problem_solving_score INTEGER,
  strengths TEXT,
  weaknesses TEXT,
  recommendation TEXT CHECK (recommendation IN ('strong_hire','hire','no_hire','strong_no_hire')),
  detailed_feedback TEXT,
  score_breakdown JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_feedback_interview ON interview_feedback(interview_id);

-- 24. VIDEO_INTERVIEW_SESSIONS
CREATE TABLE video_interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id) ON DELETE CASCADE,
  candidate_id TEXT REFERENCES users(id),
  session_token TEXT UNIQUE,
  is_proctored BOOLEAN DEFAULT false,
  proctoring_config JSONB DEFAULT '{}',
  browser_info JSONB DEFAULT '{}',
  tab_switch_count INTEGER DEFAULT 0,
  face_detection_alerts INTEGER DEFAULT 0,
  audio_anomalies INTEGER DEFAULT 0,
  screen_share_active BOOLEAN DEFAULT false,
  ai_trust_score INTEGER,
  started_at TIMESTAMP WITH TIME ZONE,
  ended_at TIMESTAMP WITH TIME ZONE,
  status TEXT CHECK (status IN ('waiting','active','paused','completed','terminated','expired')) DEFAULT 'waiting',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_video_sessions_interview ON video_interview_sessions(interview_id);

-- 25. SESSION_RECORDINGS
CREATE TABLE session_recordings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES video_interview_sessions(id) ON DELETE CASCADE,
  interview_id BIGINT REFERENCES interviews(id),
  recording_url TEXT,
  storage_provider TEXT DEFAULT 'youtube',
  youtube_video_id TEXT,
  duration_secs INTEGER DEFAULT 0,
  file_size_mb DECIMAL(10,2) DEFAULT 0,
  transcript TEXT,
  ai_analysis JSONB DEFAULT '{}',
  status TEXT CHECK (status IN ('recording','processing','ready','failed','deleted')) DEFAULT 'recording',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_recordings_session ON session_recordings(session_id);

-- 26. SUBSCRIPTION_PLANS
CREATE TABLE subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price_inr DECIMAL(10,2) DEFAULT 0,
  price_usd DECIMAL(10,2) DEFAULT 0,
  price_aed DECIMAL(10,2) DEFAULT 0,
  price_eur DECIMAL(10,2) DEFAULT 0,
  duration TEXT DEFAULT 'Monthly',
  is_active BOOLEAN DEFAULT true,
  job_posts_limit INTEGER DEFAULT 0,
  candidate_views_limit INTEGER DEFAULT 0,
  ai_screening_enabled BOOLEAN DEFAULT false,
  featured_jobs_enabled BOOLEAN DEFAULT false,
  features JSONB DEFAULT '{}',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 27. EMPLOYER_SUBSCRIPTIONS
CREATE TABLE employer_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  plan_id BIGINT REFERENCES subscription_plans(id),
  status TEXT CHECK (status IN ('active','expired','cancelled','trial','past_due')) DEFAULT 'active',
  started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE,
  cancelled_at TIMESTAMP WITH TIME ZONE,
  jobs_used INTEGER DEFAULT 0,
  payment_id BIGINT,
  auto_renew BOOLEAN DEFAULT false,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_emp_subs_employer ON employer_subscriptions(employer_id);
CREATE INDEX IF NOT EXISTS idx_emp_subs_plan ON employer_subscriptions(plan_id);

-- 28. PAY_PER_HIRE_RECORDS
CREATE TABLE pay_per_hire_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id),
  candidate_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES employer_job_posts(id),
  application_id BIGINT REFERENCES job_applications(id),
  salary_offered DECIMAL(12,2) DEFAULT 0,
  salary_currency TEXT DEFAULT 'INR',
  pph_fee DECIMAL(10,2) DEFAULT 0,
  fee_percentage DECIMAL(5,2),
  advance_amount DECIMAL(10,2) DEFAULT 0,
  post_payment_amount DECIMAL(10,2) DEFAULT 0,
  replacement_period_days INTEGER DEFAULT 90,
  replacement_deadline TIMESTAMP WITH TIME ZONE,
  agreement_url TEXT,
  status TEXT CHECK (status IN ('pending','advance_paid','candidate_joined','completed','refunded','cancelled','disputed')) DEFAULT 'pending',
  hired_date TIMESTAMP WITH TIME ZONE,
  notes TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pph_employer ON pay_per_hire_records(employer_id);
CREATE INDEX IF NOT EXISTS idx_pph_status ON pay_per_hire_records(status);

-- 29. TRANSACTIONS
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  type TEXT CHECK (type IN ('subscription','pph_advance','pph_final','credit_purchase','job_post','refund','payout','course_purchase','wallet_topup')) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency TEXT DEFAULT 'INR',
  payment_gateway TEXT,
  gateway_txn_id TEXT,
  gateway_order_id TEXT,
  status TEXT CHECK (status IN ('initiated','pending','success','failed','refunded','cancelled')) DEFAULT 'initiated',
  entity_type TEXT,
  entity_id TEXT,
  description TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_txn_user ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_txn_status ON transactions(status);
CREATE INDEX IF NOT EXISTS idx_txn_type ON transactions(type);
CREATE INDEX IF NOT EXISTS idx_txn_date ON transactions(created_at);

-- 30. WALLET
CREATE TABLE wallet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  balance DECIMAL(12,2) DEFAULT 0,
  credits INTEGER DEFAULT 0,
  currency TEXT DEFAULT 'INR',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_wallet_user ON wallet(user_id);

-- 31. WALLET_TRANSACTIONS
CREATE TABLE wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT REFERENCES wallet(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id),
  type TEXT CHECK (type IN ('credit','debit','refund','bonus','adjustment')) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  credits_change INTEGER DEFAULT 0,
  balance_after DECIMAL(12,2),
  description TEXT,
  reference_type TEXT,
  reference_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_wallet_txn_wallet ON wallet_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_wallet_txn_user ON wallet_transactions(user_id);

-- 32. PAYMENTS
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  transaction_id BIGINT REFERENCES transactions(id),
  amount DECIMAL(12,2) NOT NULL,
  currency TEXT DEFAULT 'INR',
  payment_method TEXT CHECK (payment_method IN ('razorpay','stripe','paypal','bank_transfer','upi','wallet','free')) DEFAULT 'razorpay',
  gateway_payment_id TEXT,
  gateway_signature TEXT,
  invoice_url TEXT,
  invoice_number TEXT,
  tax_amount DECIMAL(10,2) DEFAULT 0,
  discount_amount DECIMAL(10,2) DEFAULT 0,
  status TEXT CHECK (status IN ('pending','authorized','captured','failed','refunded','partially_refunded')) DEFAULT 'pending',
  paid_at TIMESTAMP WITH TIME ZONE,
  refunded_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_payments_user ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);

-- 33. STAFF_USERS
CREATE TABLE staff_users (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  department TEXT,
  designation TEXT,
  employee_code TEXT UNIQUE,
  reporting_to TEXT REFERENCES users(id),
  permissions JSONB DEFAULT '[]',
  modules_access JSONB DEFAULT '[]',
  is_active BOOLEAN DEFAULT true,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 34. STAFF_ACTIVITY
CREATE TABLE staff_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  module TEXT,
  entity_type TEXT,
  entity_id TEXT,
  details TEXT,
  metadata JSONB DEFAULT '{}',
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_staff_activity_staff ON staff_activity(staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_activity_date ON staff_activity(created_at);

-- 35. CRM_LEADS
CREATE TABLE crm_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  company TEXT,
  designation TEXT,
  source TEXT CHECK (source IN ('website','referral','linkedin','ads','cold_call','event','partner','other')) DEFAULT 'website',
  lead_type TEXT CHECK (lead_type IN ('employer','candidate','educator','partner','investor')) DEFAULT 'employer',
  status TEXT CHECK (status IN ('new','contacted','qualified','proposal','negotiation','won','lost','nurturing')) DEFAULT 'new',
  assigned_to TEXT REFERENCES users(id),
  priority TEXT CHECK (priority IN ('low','medium','high','critical')) DEFAULT 'medium',
  notes TEXT,
  follow_up_date TIMESTAMP WITH TIME ZONE,
  deal_value DECIMAL(12,2),
  tags JSONB DEFAULT '[]',
  activity_log JSONB DEFAULT '[]',
  metadata JSONB DEFAULT '{}',
  converted_user_id TEXT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_crm_leads_status ON crm_leads(status);
CREATE INDEX IF NOT EXISTS idx_crm_leads_assigned ON crm_leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_crm_leads_source ON crm_leads(source);

-- 36. NOTIFICATIONS
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT,
  type TEXT CHECK (type IN ('info','success','warning','error','action_required')) DEFAULT 'info',
  channel TEXT CHECK (channel IN ('in_app','email','sms','push','whatsapp')) DEFAULT 'in_app',
  category TEXT DEFAULT 'general',
  action_url TEXT,
  is_read BOOLEAN DEFAULT false,
  is_sent BOOLEAN DEFAULT false,
  sent_at TIMESTAMP WITH TIME ZONE,
  read_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_date ON notifications(created_at);

-- 37. ADMIN_USERS
CREATE TABLE admin_users (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  admin_level TEXT CHECK (admin_level IN ('super_admin','admin','moderator','viewer')) DEFAULT 'admin',
  permissions JSONB DEFAULT '[]',
  two_factor_enabled BOOLEAN DEFAULT false,
  last_login TIMESTAMP WITH TIME ZONE,
  login_history JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 38. ADMIN_SETTINGS
CREATE TABLE admin_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key TEXT UNIQUE NOT NULL,
  setting_value TEXT,
  setting_type TEXT CHECK (setting_type IN ('string','number','boolean','json')) DEFAULT 'string',
  category TEXT DEFAULT 'general',
  description TEXT,
  is_sensitive BOOLEAN DEFAULT false,
  updated_by TEXT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_admin_settings_key ON admin_settings(setting_key);
CREATE INDEX IF NOT EXISTS idx_admin_settings_category ON admin_settings(category);

-- 39. PLATFORM_REPORTS
CREATE TABLE platform_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type TEXT CHECK (report_type IN ('revenue','users','jobs','applications','interviews','hires','courses','support','custom')) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  date_range_start DATE,
  date_range_end DATE,
  filters JSONB DEFAULT '{}',
  report_data JSONB DEFAULT '{}',
  generated_by TEXT REFERENCES users(id),
  file_url TEXT,
  status TEXT CHECK (status IN ('generating','ready','failed','expired')) DEFAULT 'generating',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_reports_type ON platform_reports(report_type);

-- 40. ANALYTICS
CREATE TABLE analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  event_category TEXT,
  user_id TEXT,
  session_id TEXT,
  page_url TEXT,
  referrer TEXT,
  device_type TEXT,
  browser TEXT,
  country TEXT,
  city TEXT,
  ip_address TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_analytics_event ON analytics(event_name);
CREATE INDEX IF NOT EXISTS idx_analytics_user ON analytics(user_id);
CREATE INDEX IF NOT EXISTS idx_analytics_date ON analytics(created_at);

-- 41. ROUTES_REGISTRY
CREATE TABLE routes_registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL,
  icon TEXT,
  module TEXT CHECK (module IN ('candidate','employer','admin','staff','educator','upskill','public','auth')) NOT NULL,
  parent_path TEXT,
  sort_order INTEGER DEFAULT 0,
  is_sidebar BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  roles_allowed JSONB DEFAULT '["admin"]',
  permissions_required JSONB DEFAULT '[]',
  component_name TEXT,
  badge_key TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_routes_module ON routes_registry(module);
CREATE INDEX IF NOT EXISTS idx_routes_path ON routes_registry(path);

-- 42. EMAIL_LOGS
CREATE TABLE email_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_email TEXT NOT NULL,
  to_name TEXT,
  from_email TEXT,
  subject TEXT NOT NULL,
  body_html TEXT,
  body_text TEXT,
  template_name TEXT,
  template_vars JSONB DEFAULT '{}',
  provider TEXT DEFAULT 'smtp',
  provider_message_id TEXT,
  status TEXT CHECK (status IN ('queued','sent','delivered','bounced','failed','opened','clicked')) DEFAULT 'queued',
  error_message TEXT,
  opened_at TIMESTAMP WITH TIME ZONE,
  clicked_at TIMESTAMP WITH TIME ZONE,
  sent_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_email_logs_to ON email_logs(to_email);
CREATE INDEX IF NOT EXISTS idx_email_logs_status ON email_logs(status);
CREATE INDEX IF NOT EXISTS idx_email_logs_date ON email_logs(created_at);

-- ============================================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignment_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE educators ENABLE ROW LEVEL SECURITY;
ALTER TABLE educator_payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE employers ENABLE ROW LEVEL SECURITY;
ALTER TABLE employer_job_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE employer_activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE screening_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_interview_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_recordings ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE employer_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pay_per_hire_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallet ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE routes_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_logs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- PUBLIC ACCESS POLICIES
-- ============================================================
CREATE POLICY "Public Access" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON user_profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON candidates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON candidate_progress FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON candidate_certificates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON candidate_assessments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON candidate_activity_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON courses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON course_lessons FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON course_quizzes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON course_assignments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON assignment_submissions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON live_classes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON educators FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON educator_payouts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON employers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON employer_job_posts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON employer_activity_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON job_applications FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON screening_results FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON interviews FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON interview_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON interview_feedback FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON video_interview_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON session_recordings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON subscription_plans FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON employer_subscriptions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON pay_per_hire_records FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON wallet FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON wallet_transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON payments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON staff_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON staff_activity FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON crm_leads FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON notifications FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON admin_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON admin_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON platform_reports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON analytics FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON routes_registry FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON email_logs FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- FRESH INSTALL COMPLETE - 42 TABLES CREATED
-- ============================================================
