-- ============================================================
-- HIREGO AI - MISSING TABLES MIGRATION (Idempotent 2.0)
-- Safely adds missing tables and policies without errors.
-- Run this block in Supabase SQL Editor.
-- ============================================================

-- 1. USER PROFILES
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  bio TEXT,
  title TEXT,
  location TEXT,
  date_of_birth DATE,
  gender TEXT,
  current_address TEXT,
  permanent_address TEXT,
  linkedin_url TEXT,
  github_url TEXT,
  portfolio_url TEXT,
  resume_url TEXT,
  skills JSONB DEFAULT '[]',
  languages JSONB DEFAULT '[]',
  preferences JSONB DEFAULT '{}',
  profile_completion INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_profiles' AND policyname = 'Public Access') THEN
        CREATE POLICY "Public Access" ON public.user_profiles FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;


-- 2. CANDIDATE MODULE
CREATE TABLE IF NOT EXISTS public.candidate_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  course_id BIGINT,
  lesson_id BIGINT,
  quiz_id BIGINT,
  progress_pct INTEGER DEFAULT 0,
  status TEXT CHECK (status IN ('not_started','in_progress','completed')) DEFAULT 'not_started',
  score INTEGER,
  time_spent_mins INTEGER DEFAULT 0,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.candidate_progress ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'candidate_progress' AND policyname = 'Public Access CP') THEN
        CREATE POLICY "Public Access CP" ON public.candidate_progress FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.candidate_certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  course_id BIGINT,
  certificate_url TEXT,
  certificate_code TEXT UNIQUE,
  issued_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expiry_date TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}'
);
ALTER TABLE public.candidate_certificates ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'candidate_certificates' AND policyname = 'Public Access CC') THEN
        CREATE POLICY "Public Access CC" ON public.candidate_certificates FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.candidate_activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  metadata JSONB DEFAULT '{}',
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.candidate_activity_log ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'candidate_activity_log' AND policyname = 'Public Access CAL') THEN
        CREATE POLICY "Public Access CAL" ON public.candidate_activity_log FOR ALL USING (true);
    END IF;
END $$;


-- 3. COURSE MODULE
CREATE TABLE IF NOT EXISTS public.course_lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT, 
  title TEXT NOT NULL,
  description TEXT,
  content_type TEXT CHECK (content_type IN ('video','text','pdf','interactive','quiz')) DEFAULT 'video',
  content_url TEXT,
  content_text TEXT,
  duration_mins INTEGER DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  is_free_preview BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.course_lessons ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'course_lessons' AND policyname = 'Public Access CL') THEN
        CREATE POLICY "Public Access CL" ON public.course_lessons FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.course_quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT,
  lesson_id BIGINT REFERENCES course_lessons(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  questions JSONB DEFAULT '[]',
  passing_score INTEGER DEFAULT 60,
  time_limit_mins INTEGER DEFAULT 30,
  max_attempts INTEGER DEFAULT 3,
  sort_order INTEGER DEFAULT 0,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.course_quizzes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'course_quizzes' AND policyname = 'Public Access CQ') THEN
        CREATE POLICY "Public Access CQ" ON public.course_quizzes FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.course_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT,
  title TEXT NOT NULL,
  description TEXT,
  instructions TEXT,
  due_date TIMESTAMP WITH TIME ZONE,
  max_score INTEGER DEFAULT 100,
  rubric JSONB DEFAULT '{}',
  attachments JSONB DEFAULT '[]',
  sort_order INTEGER DEFAULT 0,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.course_assignments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'course_assignments' AND policyname = 'Public Access CAs') THEN
        CREATE POLICY "Public Access CAs" ON public.course_assignments FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.assignment_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT REFERENCES course_assignments(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  submission_url TEXT,
  submission_text TEXT,
  attachments JSONB DEFAULT '[]',
  score INTEGER,
  feedback TEXT,
  graded_by TEXT REFERENCES users(id),
  status TEXT CHECK (status IN ('submitted','under_review','graded','returned','late')) DEFAULT 'submitted',
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  graded_at TIMESTAMP WITH TIME ZONE
);
ALTER TABLE public.assignment_submissions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'assignment_submissions' AND policyname = 'Public Access AS') THEN
        CREATE POLICY "Public Access AS" ON public.assignment_submissions FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.live_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT,
  educator_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
  duration_mins INTEGER DEFAULT 60,
  meeting_url TEXT,
  recording_url TEXT,
  max_attendees INTEGER DEFAULT 100,
  current_attendees INTEGER DEFAULT 0,
  status TEXT CHECK (status IN ('scheduled','live','completed','cancelled')) DEFAULT 'scheduled',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.live_classes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'live_classes' AND policyname = 'Public Access LC') THEN
        CREATE POLICY "Public Access LC" ON public.live_classes FOR ALL USING (true);
    END IF;
END $$;


-- 4. EMPLOYER & JOBS
CREATE TABLE IF NOT EXISTS public.employer_job_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  requirements TEXT,
  responsibilities TEXT,
  skills JSONB DEFAULT '[]',
  location TEXT,
  country TEXT DEFAULT 'IN',
  work_mode TEXT CHECK (work_mode IN ('On-site','Remote','Hybrid')) DEFAULT 'Remote',
  employment_type TEXT CHECK (employment_type IN ('Full-time','Part-time','Contract','Freelance','Internship')) DEFAULT 'Full-time',
  experience_min INTEGER DEFAULT 0,
  experience_max INTEGER,
  salary_min DECIMAL(12,2),
  salary_max DECIMAL(12,2),
  salary_currency TEXT DEFAULT 'INR',
  education_required JSONB DEFAULT '[]',
  benefits JSONB DEFAULT '[]',
  job_type TEXT DEFAULT 'free',
  plan_id BIGINT,
  status TEXT CHECK (status IN ('active','draft','closed','archived','expired','under_review')) DEFAULT 'active',
  is_featured BOOLEAN DEFAULT false,
  is_urgent BOOLEAN DEFAULT false,
  application_count INTEGER DEFAULT 0,
  views_count INTEGER DEFAULT 0,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.employer_job_posts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'employer_job_posts' AND policyname = 'Public Access EJP') THEN
        CREATE POLICY "Public Access EJP" ON public.employer_job_posts FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.employer_activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  metadata JSONB DEFAULT '{}',
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.employer_activity_log ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'employer_activity_log' AND policyname = 'Public Access EAL') THEN
        CREATE POLICY "Public Access EAL" ON public.employer_activity_log FOR ALL USING (true);
    END IF;
END $$;


-- 5. RECRUITMENT & INTERVIEWS
CREATE TABLE IF NOT EXISTS public.job_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES employer_job_posts(id) ON DELETE CASCADE,
  candidate_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  resume_url TEXT,
  cover_letter TEXT,
  match_score INTEGER,
  ai_screening_score INTEGER,
  status TEXT CHECK (status IN ('applied','pending','screened','shortlisted','interview_scheduled','interviewed','offered','hired','rejected','withdrawn')) DEFAULT 'applied',
  rejection_reason TEXT,
  notes TEXT,
  metadata JSONB DEFAULT '{}',
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(job_id, candidate_id)
);
ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'job_applications' AND policyname = 'Public Access JA') THEN
        CREATE POLICY "Public Access JA" ON public.job_applications FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.screening_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT REFERENCES job_applications(id) ON DELETE CASCADE,
  candidate_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES employer_job_posts(id),
  screening_type TEXT CHECK (screening_type IN ('ai_resume','ai_skill','ai_behavioral','manual','coding_test')) DEFAULT 'ai_resume',
  overall_score INTEGER,
  skill_match_score INTEGER,
  experience_match_score INTEGER,
  education_match_score INTEGER,
  score_breakdown JSONB DEFAULT '{}',
  ai_summary TEXT,
  recommendation TEXT CHECK (recommendation IN ('strong_yes','yes','maybe','no','strong_no')),
  screened_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.screening_results ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'screening_results' AND policyname = 'Public Access SR') THEN
        CREATE POLICY "Public Access SR" ON public.screening_results FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.interview_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  event_data JSONB DEFAULT '{}',
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.interview_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'interview_logs' AND policyname = 'Public Access IL') THEN
        CREATE POLICY "Public Access IL" ON public.interview_logs FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.interview_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id) ON DELETE CASCADE,
  interviewer_id TEXT REFERENCES users(id),
  overall_rating INTEGER CHECK (overall_rating >= 1 AND overall_rating <= 5),
  technical_score INTEGER,
  communication_score INTEGER,
  cultural_fit_score INTEGER,
  problem_solving_score INTEGER,
  strengths TEXT,
  weaknesses TEXT,
  recommendation TEXT CHECK (recommendation IN ('strong_hire','hire','no_hire','strong_no_hire')),
  detailed_feedback TEXT,
  score_breakdown JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.interview_feedback ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'interview_feedback' AND policyname = 'Public Access IF') THEN
        CREATE POLICY "Public Access IF" ON public.interview_feedback FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.video_interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id) ON DELETE CASCADE,
  candidate_id TEXT REFERENCES users(id),
  session_token TEXT UNIQUE,
  is_proctored BOOLEAN DEFAULT false,
  proctoring_config JSONB DEFAULT '{}',
  browser_info JSONB DEFAULT '{}',
  tab_switch_count INTEGER DEFAULT 0,
  face_detection_alerts INTEGER DEFAULT 0,
  audio_anomalies INTEGER DEFAULT 0,
  screen_share_active BOOLEAN DEFAULT false,
  ai_trust_score INTEGER,
  started_at TIMESTAMP WITH TIME ZONE,
  ended_at TIMESTAMP WITH TIME ZONE,
  status TEXT CHECK (status IN ('waiting','active','paused','completed','terminated','expired')) DEFAULT 'waiting',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.video_interview_sessions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'video_interview_sessions' AND policyname = 'Public Access VIS') THEN
        CREATE POLICY "Public Access VIS" ON public.video_interview_sessions FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.session_recordings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES video_interview_sessions(id) ON DELETE CASCADE,
  interview_id BIGINT REFERENCES interviews(id),
  recording_url TEXT,
  storage_provider TEXT DEFAULT 'youtube',
  youtube_video_id TEXT,
  duration_secs INTEGER DEFAULT 0,
  file_size_mb DECIMAL(10,2) DEFAULT 0,
  transcript TEXT,
  ai_analysis JSONB DEFAULT '{}',
  status TEXT CHECK (status IN ('recording','processing','ready','failed','deleted')) DEFAULT 'recording',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.session_recordings ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'session_recordings' AND policyname = 'Public Access REC') THEN
        CREATE POLICY "Public Access REC" ON public.session_recordings FOR ALL USING (true);
    END IF;
END $$;


-- 6. FINANCE
CREATE TABLE IF NOT EXISTS public.employer_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  plan_id BIGINT REFERENCES subscription_plans(id),
  status TEXT CHECK (status IN ('active','expired','cancelled','trial','past_due')) DEFAULT 'active',
  started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE,
  cancelled_at TIMESTAMP WITH TIME ZONE,
  jobs_used INTEGER DEFAULT 0,
  payment_id BIGINT,
  auto_renew BOOLEAN DEFAULT false,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.employer_subscriptions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'employer_subscriptions' AND policyname = 'Public Access ES') THEN
        CREATE POLICY "Public Access ES" ON public.employer_subscriptions FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.pay_per_hire_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id TEXT REFERENCES users(id),
  candidate_id TEXT REFERENCES users(id),
  job_id BIGINT REFERENCES employer_job_posts(id),
  application_id BIGINT REFERENCES job_applications(id),
  salary_offered DECIMAL(12,2) DEFAULT 0,
  salary_currency TEXT DEFAULT 'INR',
  pph_fee DECIMAL(10,2) DEFAULT 0,
  fee_percentage DECIMAL(5,2),
  advance_amount DECIMAL(10,2) DEFAULT 0,
  post_payment_amount DECIMAL(10,2) DEFAULT 0,
  replacement_period_days INTEGER DEFAULT 90,
  replacement_deadline TIMESTAMP WITH TIME ZONE,
  agreement_url TEXT,
  status TEXT CHECK (status IN ('pending','advance_paid','candidate_joined','completed','refunded','cancelled','disputed')) DEFAULT 'pending',
  hired_date TIMESTAMP WITH TIME ZONE,
  notes TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.pay_per_hire_records ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'pay_per_hire_records' AND policyname = 'Public Access PPH') THEN
        CREATE POLICY "Public Access PPH" ON public.pay_per_hire_records FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  type TEXT CHECK (type IN ('subscription','pph_advance','pph_final','credit_purchase','job_post','refund','payout','course_purchase','wallet_topup')) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency TEXT DEFAULT 'INR',
  payment_gateway TEXT,
  gateway_txn_id TEXT,
  gateway_order_id TEXT,
  status TEXT CHECK (status IN ('initiated','pending','success','failed','refunded','cancelled')) DEFAULT 'initiated',
  entity_type TEXT,
  entity_id TEXT,
  description TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'transactions' AND policyname = 'Public Access TX') THEN
        CREATE POLICY "Public Access TX" ON public.transactions FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.wallet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  balance DECIMAL(12,2) DEFAULT 0,
  credits INTEGER DEFAULT 0,
  currency TEXT DEFAULT 'INR',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.wallet ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'wallet' AND policyname = 'Public Access WAL') THEN
        CREATE POLICY "Public Access WAL" ON public.wallet FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT REFERENCES wallet(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id),
  type TEXT CHECK (type IN ('credit','debit','refund','bonus','adjustment')) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  credits_change INTEGER DEFAULT 0,
  balance_after DECIMAL(12,2),
  description TEXT,
  reference_type TEXT,
  reference_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'wallet_transactions' AND policyname = 'Public Access WT') THEN
        CREATE POLICY "Public Access WT" ON public.wallet_transactions FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  transaction_id BIGINT REFERENCES transactions(id),
  amount DECIMAL(12,2) NOT NULL,
  currency TEXT DEFAULT 'INR',
  payment_method TEXT CHECK (payment_method IN ('razorpay','stripe','paypal','bank_transfer','upi','wallet','free')) DEFAULT 'razorpay',
  gateway_payment_id TEXT,
  gateway_signature TEXT,
  invoice_url TEXT,
  invoice_number TEXT,
  tax_amount DECIMAL(10,2) DEFAULT 0,
  discount_amount DECIMAL(10,2) DEFAULT 0,
  status TEXT CHECK (status IN ('pending','authorized','captured','failed','refunded','partially_refunded')) DEFAULT 'pending',
  paid_at TIMESTAMP WITH TIME ZONE,
  refunded_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'payments' AND policyname = 'Public Access PAY') THEN
        CREATE POLICY "Public Access PAY" ON public.payments FOR ALL USING (true);
    END IF;
END $$;


-- 7. ADMIN & LOGS
CREATE TABLE IF NOT EXISTS public.staff_users (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  department TEXT,
  designation TEXT,
  employee_code TEXT UNIQUE,
  reporting_to TEXT REFERENCES users(id),
  permissions JSONB DEFAULT '[]',
  modules_access JSONB DEFAULT '[]',
  is_active BOOLEAN DEFAULT true,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.staff_users ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'staff_users' AND policyname = 'Public Access SU') THEN
        CREATE POLICY "Public Access SU" ON public.staff_users FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.staff_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  module TEXT,
  entity_type TEXT,
  entity_id TEXT,
  details TEXT,
  metadata JSONB DEFAULT '{}',
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.staff_activity ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'staff_activity' AND policyname = 'Public Access SA') THEN
        CREATE POLICY "Public Access SA" ON public.staff_activity FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.crm_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  company TEXT,
  designation TEXT,
  source TEXT CHECK (source IN ('website','referral','linkedin','ads','cold_call','event','partner','other')) DEFAULT 'website',
  lead_type TEXT CHECK (lead_type IN ('employer','candidate','educator','partner','investor')) DEFAULT 'employer',
  status TEXT CHECK (status IN ('new','contacted','qualified','proposal','negotiation','won','lost','nurturing')) DEFAULT 'new',
  assigned_to TEXT REFERENCES users(id),
  priority TEXT CHECK (priority IN ('low','medium','high','critical')) DEFAULT 'medium',
  notes TEXT,
  follow_up_date TIMESTAMP WITH TIME ZONE,
  deal_value DECIMAL(12,2),
  tags JSONB DEFAULT '[]',
  activity_log JSONB DEFAULT '[]',
  metadata JSONB DEFAULT '{}',
  converted_user_id TEXT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.crm_leads ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'crm_leads' AND policyname = 'Public Access CRM') THEN
        CREATE POLICY "Public Access CRM" ON public.crm_leads FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT,
  type TEXT CHECK (type IN ('info','success','warning','error','action_required')) DEFAULT 'info',
  channel TEXT CHECK (channel IN ('in_app','email','sms','push','whatsapp')) DEFAULT 'in_app',
  category TEXT DEFAULT 'general',
  action_url TEXT,
  is_read BOOLEAN DEFAULT false,
  is_sent BOOLEAN DEFAULT false,
  sent_at TIMESTAMP WITH TIME ZONE,
  read_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'notifications' AND policyname = 'Public Access Notif') THEN
        CREATE POLICY "Public Access Notif" ON public.notifications FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.admin_users (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  admin_level TEXT CHECK (admin_level IN ('super_admin','admin','moderator','viewer')) DEFAULT 'admin',
  permissions JSONB DEFAULT '[]',
  two_factor_enabled BOOLEAN DEFAULT false,
  last_login TIMESTAMP WITH TIME ZONE,
  login_history JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'admin_users' AND policyname = 'Public Access AU') THEN
        CREATE POLICY "Public Access AU" ON public.admin_users FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.admin_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key TEXT UNIQUE NOT NULL,
  setting_value TEXT,
  setting_type TEXT CHECK (setting_type IN ('string','number','boolean','json')) DEFAULT 'string',
  category TEXT DEFAULT 'general',
  description TEXT,
  is_sensitive BOOLEAN DEFAULT false,
  updated_by TEXT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'admin_settings' AND policyname = 'Public Access AS') THEN
        CREATE POLICY "Public Access AS" ON public.admin_settings FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.platform_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type TEXT CHECK (report_type IN ('revenue','users','jobs','applications','interviews','hires','courses','support','custom')) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  date_range_start DATE,
  date_range_end DATE,
  filters JSONB DEFAULT '{}',
  report_data JSONB DEFAULT '{}',
  generated_by TEXT REFERENCES users(id),
  file_url TEXT,
  status TEXT CHECK (status IN ('generating','ready','failed','expired')) DEFAULT 'generating',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.platform_reports ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'platform_reports' AND policyname = 'Public Access PR') THEN
        CREATE POLICY "Public Access PR" ON public.platform_reports FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  event_category TEXT,
  user_id TEXT,
  session_id TEXT,
  page_url TEXT,
  referrer TEXT,
  device_type TEXT,
  browser TEXT,
  country TEXT,
  city TEXT,
  ip_address TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'analytics' AND policyname = 'Public Access AN') THEN
        CREATE POLICY "Public Access AN" ON public.analytics FOR ALL USING (true);
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS public.email_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_email TEXT NOT NULL,
  to_name TEXT,
  from_email TEXT,
  subject TEXT NOT NULL,
  body_html TEXT,
  body_text TEXT,
  template_name TEXT,
  template_vars JSONB DEFAULT '{}',
  provider TEXT DEFAULT 'smtp',
  provider_message_id TEXT,
  status TEXT CHECK (status IN ('queued','sent','delivered','bounced','failed','opened','clicked')) DEFAULT 'queued',
  error_message TEXT,
  opened_at TIMESTAMP WITH TIME ZONE,
  clicked_at TIMESTAMP WITH TIME ZONE,
  sent_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.email_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'email_logs' AND policyname = 'Public Access EL') THEN
        CREATE POLICY "Public Access EL" ON public.email_logs FOR ALL USING (true);
    END IF;
END $$;
