-- =====================================================
-- MIGRATION 001: Create tables referenced in code but missing from schema
-- Run this in your Supabase SQL Editor
-- =====================================================

-- 1. candidate_experience: Stores work history shown on Profile page
CREATE TABLE IF NOT EXISTS candidate_experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  description TEXT,
  start_date TEXT,
  end_date TEXT,
  is_current BOOLEAN DEFAULT FALSE,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_candidate_experience_user ON candidate_experience(user_id);

-- 2. candidate_skills: Stores skills shown on Profile page  
CREATE TABLE IF NOT EXISTS candidate_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  skill TEXT NOT NULL,
  proficiency TEXT CHECK (proficiency IN ('beginner','intermediate','advanced','expert')) DEFAULT 'intermediate',
  years_of_experience INTEGER DEFAULT 0,
  verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, skill)
);
CREATE INDEX IF NOT EXISTS idx_candidate_skills_user ON candidate_skills(user_id);

-- 3. assessment_results: Stores AI assessment results referenced in candidate stats
CREATE TABLE IF NOT EXISTS assessment_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  assessment_type TEXT CHECK (assessment_type IN ('coding','behavioral','technical','aptitude','video')) DEFAULT 'coding',
  score INTEGER,
  max_score INTEGER DEFAULT 100,
  duration_seconds INTEGER,
  result_data JSONB DEFAULT '{}',
  passed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_assessment_results_user ON assessment_results(user_id);

-- 4. Add video_resume_url column to candidates table (if missing)
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS video_resume_url TEXT;

-- 5. Enable RLS on new tables
ALTER TABLE candidate_experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies: Users can read/write their own data
DO $$
BEGIN
  -- candidate_experience policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'candidate_experience_select_own' AND tablename = 'candidate_experience') THEN
    CREATE POLICY candidate_experience_select_own ON candidate_experience FOR SELECT USING (user_id = auth.uid()::text);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'candidate_experience_insert_own' AND tablename = 'candidate_experience') THEN
    CREATE POLICY candidate_experience_insert_own ON candidate_experience FOR INSERT WITH CHECK (user_id = auth.uid()::text);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'candidate_experience_update_own' AND tablename = 'candidate_experience') THEN
    CREATE POLICY candidate_experience_update_own ON candidate_experience FOR UPDATE USING (user_id = auth.uid()::text);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'candidate_experience_delete_own' AND tablename = 'candidate_experience') THEN
    CREATE POLICY candidate_experience_delete_own ON candidate_experience FOR DELETE USING (user_id = auth.uid()::text);
  END IF;

  -- candidate_skills policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'candidate_skills_select_own' AND tablename = 'candidate_skills') THEN
    CREATE POLICY candidate_skills_select_own ON candidate_skills FOR SELECT USING (user_id = auth.uid()::text);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'candidate_skills_insert_own' AND tablename = 'candidate_skills') THEN
    CREATE POLICY candidate_skills_insert_own ON candidate_skills FOR INSERT WITH CHECK (user_id = auth.uid()::text);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'candidate_skills_update_own' AND tablename = 'candidate_skills') THEN
    CREATE POLICY candidate_skills_update_own ON candidate_skills FOR UPDATE USING (user_id = auth.uid()::text);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'candidate_skills_delete_own' AND tablename = 'candidate_skills') THEN
    CREATE POLICY candidate_skills_delete_own ON candidate_skills FOR DELETE USING (user_id = auth.uid()::text);
  END IF;

  -- assessment_results policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'assessment_results_select_own' AND tablename = 'assessment_results') THEN
    CREATE POLICY assessment_results_select_own ON assessment_results FOR SELECT USING (user_id = auth.uid()::text);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'assessment_results_insert_own' AND tablename = 'assessment_results') THEN
    CREATE POLICY assessment_results_insert_own ON assessment_results FOR INSERT WITH CHECK (user_id = auth.uid()::text);
  END IF;
END
$$;

-- Done! Verify:
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('candidate_experience', 'candidate_skills', 'assessment_results');
