-- =====================================================
-- MIGRATION 002: Complete Referral & Payout Architecture
-- Implements the PPH and Subscription Referral System tracking
-- =====================================================

-- 1. referral_links: Stores unique codes for users
CREATE TABLE IF NOT EXISTS referral_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    referral_code TEXT UNIQUE NOT NULL,
    total_clicks INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id)
);
CREATE INDEX IF NOT EXISTS idx_referral_links_code ON referral_links(referral_code);

-- 2. referrals_tracking: First-touch attribution mapping
CREATE TABLE IF NOT EXISTS referrals_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id TEXT REFERENCES users(id) ON DELETE CASCADE, -- the person who shared the link
    referred_user_id TEXT REFERENCES users(id) ON DELETE CASCADE, -- the person who signed up
    referral_type TEXT CHECK (referral_type IN ('candidate', 'company')) NOT NULL,
    status TEXT CHECK (status IN ('registered', 'in_process', 'hired', 'rejected', 'cancelled')) DEFAULT 'registered',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(referred_user_id) -- Only one referrer per user (first-touch attribution)
);
CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals_tracking(referrer_id);

-- 3. referral_rules: Admin configurable commission payouts
CREATE TABLE IF NOT EXISTS referral_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_type TEXT CHECK (rule_type IN ('candidate_pph_role', 'company_pph_onboard', 'company_subscription')) NOT NULL,
    job_role TEXT, -- e.g., 'Software Engineer' (nullable, applies to candidate_pph_role)
    subscription_tier TEXT, -- e.g., 'premium' (nullable, applies to company_subscription)
    reward_type TEXT CHECK (reward_type IN ('fixed', 'percentage')) NOT NULL DEFAULT 'fixed',
    reward_amount NUMERIC NOT NULL, -- The dollar amount or percentage
    lock_in_days INTEGER DEFAULT 0, -- e.g. 90 days for candidate lock-in
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. referral_payouts: The master ledger tracking lock-ins and money flow
CREATE TABLE IF NOT EXISTS referral_payouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referral_id BIGINT REFERENCES referrals_tracking(id) ON DELETE CASCADE,
    referrer_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    
    -- Context of the reward
    job_application_id BIGINT REFERENCES job_applications(id) ON DELETE SET NULL, -- For candidate hire
    invoice_id TEXT, -- For tracking if the company paid the PPH/Subscription fee
    
    -- Commission details
    amount NUMERIC NOT NULL,
    status TEXT CHECK (status IN ('pending_lock_in', 'lock_in_completed', 'approved', 'paid', 'cancelled')) DEFAULT 'pending_lock_in',
    
    -- Lock-in tracking
    lock_in_start_date TIMESTAMP WITH TIME ZONE,
    lock_in_end_date TIMESTAMP WITH TIME ZONE,
    company_paid_fee BOOLEAN DEFAULT FALSE,
    
    -- Processing
    cancellation_reason TEXT,
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_payouts_referrer ON referral_payouts(referrer_id);

-- =====================================================
-- RLS POLICIES FOR REFERRAL TABLES
-- =====================================================

-- Turn on Row Level Security
ALTER TABLE referral_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_payouts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  -- referral_links
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'referral_links_select_own') THEN
    CREATE POLICY referral_links_select_own ON referral_links FOR SELECT USING (user_id = auth.uid()::text);
  END IF;
  
  -- referral_tracking: Users can see who they referred.
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'referrals_tracking_select_referrer') THEN
    CREATE POLICY referrals_tracking_select_referrer ON referrals_tracking FOR SELECT USING (referrer_id = auth.uid()::text);
  END IF;

  -- referral_rules: Public read so users know what they can earn
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'referral_rules_select_all') THEN
    CREATE POLICY referral_rules_select_all ON referral_rules FOR SELECT USING (is_active = TRUE);
  END IF;
  
  -- referral_payouts: Users can see their own earnings
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'referral_payouts_select_own') THEN
    CREATE POLICY referral_payouts_select_own ON referral_payouts FOR SELECT USING (referrer_id = auth.uid()::text);
  END IF;
END
$$;

-- Seed a default admin rule just to test the logic
INSERT INTO referral_rules (rule_type, job_role, reward_type, reward_amount, lock_in_days)
VALUES ('candidate_pph_role', 'Default', 'fixed', 500, 90)
ON CONFLICT DO NOTHING;
